version: "2"
services:
  smarthack_node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
